Repository enflujo/imagina-ninezya, pull requests merged in 2023-11, with the labels that each got.

#47 ✨ Pintar mapa detalle depto al elegir municipio
  aplicaciones/www/src/componentes/Mapa.astro
  aplicaciones/www/src/componentes/MapaDetalle.ts
Labels: front-end :art:

#80 🐩 íconos oficiales de la marca NiñezYA
  aplicaciones/www/estaticos/iconos/ya1.svg
  aplicaciones/www/estaticos/iconos/ya10.svg
  aplicaciones/www/estaticos/iconos/ya2.svg
  aplicaciones/www/estaticos/iconos/ya3.svg
  aplicaciones/www/estaticos/iconos/ya4.svg
  aplicaciones/www/estaticos/iconos/ya5.svg
  aplicaciones/www/estaticos/iconos/ya6.svg
  aplicaciones/www/estaticos/iconos/ya7.svg
  aplicaciones/www/estaticos/iconos/ya8.svg
  aplicaciones/www/estaticos/iconos/ya9.svg
  aplicaciones/www/src/scss/estilos.scss
Labels: :mega: URGENTE!, ui :ocean:

#78 🍭 colores para línea de tiempo y selección
  aplicaciones/www/src/scss/estilos.scss
Labels: :mega: URGENTE!, ui :ocean:

#83 📝 Avances en fichas técnicas indicadores
  aplicaciones/www/src/componentes/FichaTecnica.astro
  aplicaciones/www/src/datosVisibles/indicadores.ts
  aplicaciones/www/src/pages/[ya]/[indicador].astro
Labels: front-end :art:

#86 🦤 Créditos y otras cositas
  aplicaciones/www/estaticos/iconos/ya1.svg
  aplicaciones/www/estaticos/imagenes/Antioquia_horizontal.webp
  aplicaciones/www/estaticos/imagenes/Imagina.webp
  aplicaciones/www/estaticos/imagenes/Nacional_horizontal.webp
  aplicaciones/www/estaticos/imagenes/logoNinezYa.webp
  aplicaciones/www/estaticos/imagenes/logo_enflujo.svg
  aplicaciones/www/estaticos/imagenes/mapa.svg
  aplicaciones/www/estaticos/imagenes/mapa2.svg
  aplicaciones/www/estaticos/imagenes/mapa3.svg
  aplicaciones/www/src/pages/creditos.astro
  aplicaciones/www/src/pages/index.astro
Labels: ui :ocean:

#87 😵‍💫 boceto chirri de página datos
  aplicaciones/www/estaticos/imagenes/icono-descarga.svg
  aplicaciones/www/src/pages/creditos.astro
  aplicaciones/www/src/pages/datos.astro
Labels: ui :ocean:

#89 🪲cargados archivos favicon
  aplicaciones/www/estaticos/apple-touch-icon.png
  aplicaciones/www/estaticos/favicon.ico
  aplicaciones/www/estaticos/favicon.svg
  aplicaciones/www/estaticos/icono_192.png
  aplicaciones/www/estaticos/icono_512.png
Labels: ui :ocean:

#90 🐛 Convertir enlaces en enlaces en ficha técnica
  aplicaciones/www/src/componentes/DescripcionYa.astro
  aplicaciones/www/src/componentes/FichaTecnica.astro
  aplicaciones/www/src/pages/[ya]/[indicador].astro
Labels: bicho :bug:, ui :ocean:

#91 🐛 Cambiar nombre eje Y
  aplicaciones/www/src/componentes/Linea.ts
  aplicaciones/www/src/componentes/LineaTiempo.astro
  aplicaciones/www/src/datosVisibles/indicadores.ts
Labels: bicho :bug:

#97 🐛 primeras imágenes SEO
  aplicaciones/www/estaticos/imagenes/SEO_EnFlujo.webp
  aplicaciones/www/estaticos/imagenes/SEO_NinezYA.webp
  aplicaciones/www/estaticos/imagenes/SEO_general.webp
  aplicaciones/www/estaticos/imagenes/SEO_imagina.webp
  aplicaciones/www/src/plantillas/DatosEstructurados.astro
  aplicaciones/www/src/plantillas/Principal.astro
Labels: front-end :art:

#108 🐛 Corregir eje Y de línea de tiempo
  aplicaciones/www/src/componentes/Encabezado.astro
  aplicaciones/www/src/componentes/Linea.ts
  aplicaciones/www/src/componentes/LineaTiempo.astro
  aplicaciones/www/src/datosVisibles/indicadores.ts
  aplicaciones/www/src/pages/[ya]/[indicador].astro
Labels: bicho :bug:, front-end :art:

#109 🐛 Descargar archivos de datos
  aplicaciones/procesador/fuente/aplicacion.ts
  aplicaciones/procesador/fuente/datosDescarga.ts
  aplicaciones/procesador/package.json
  aplicaciones/www/src/datosVisibles/indicadores.ts
  aplicaciones/www/src/datosVisibles/pesosArchivos.json
  aplicaciones/www/src/pages/datos.astro
  package.json
Labels: api :evergreen_tree:, bicho :bug:

#110 🐯 créditos, cortes iniciados, párrafo bienvenida y logos exportados
  aplicaciones/www/estaticos/imagenes/antioquia_1_1.webp
  aplicaciones/www/estaticos/imagenes/antioquia_1_2.webp
  aplicaciones/www/estaticos/imagenes/antioquia_1_3.webp
  aplicaciones/www/estaticos/imagenes/antioquia_1_4.webp
  aplicaciones/www/estaticos/imagenes/antioquia_1_5.webp
  aplicaciones/www/estaticos/imagenes/antioquia_1_6.webp
  aplicaciones/www/estaticos/imagenes/antioquia_2_1.webp
  aplicaciones/www/estaticos/imagenes/antioquia_2_2.webp
  aplicaciones/www/estaticos/imagenes/antioquia_2_3.webp
  aplicaciones/www/estaticos/imagenes/antioquia_2_4.webp
  aplicaciones/www/estaticos/imagenes/antioquia_2_5.webp
  aplicaciones/www/estaticos/imagenes/antioquia_3_1.webp
  aplicaciones/www/estaticos/imagenes/antioquia_3_2.webp
  aplicaciones/www/estaticos/imagenes/antioquia_3_3.webp
  aplicaciones/www/estaticos/imagenes/antioquia_3_4.webp
  aplicaciones/www/estaticos/imagenes/antioquia_3_5.webp
  aplicaciones/www/estaticos/imagenes/enflujo_andes.svg
  aplicaciones/www/estaticos/imagenes/nacional_1_1.webp
  aplicaciones/www/estaticos/imagenes/nacional_1_2.webp
  aplicaciones/www/estaticos/imagenes/nacional_1_3.webp
  aplicaciones/www/estaticos/imagenes/nacional_1_4.webp
  aplicaciones/www/estaticos/imagenes/nacional_1_5.webp
  aplicaciones/www/estaticos/imagenes/nacional_2_1.webp
  aplicaciones/www/estaticos/imagenes/nacional_2_2.webp
  aplicaciones/www/estaticos/imagenes/nacional_2_3.webp
  aplicaciones/www/estaticos/imagenes/nacional_2_4.webp
  aplicaciones/www/estaticos/imagenes/nacional_2_5.webp
  aplicaciones/www/estaticos/imagenes/nacional_3_1.webp
  aplicaciones/www/estaticos/imagenes/nacional_3_2.webp
  aplicaciones/www/estaticos/imagenes/nacional_3_3.webp
  aplicaciones/www/estaticos/imagenes/nacional_3_4.webp
  aplicaciones/www/estaticos/imagenes/nacional_3_5.webp
  aplicaciones/www/estaticos/imagenes/nacional_4_1.webp
  aplicaciones/www/estaticos/imagenes/nacional_4_2.webp
  aplicaciones/www/estaticos/imagenes/nacional_4_3.webp
  aplicaciones/www/estaticos/imagenes/nacional_4_4.webp
  aplicaciones/www/src/pages/creditos.astro
  aplicaciones/www/src/pages/index.astro
  aplicaciones/www/src/plantillas/Principal.astro
  aplicaciones/www/src/scss/_constantes.scss
Labels: ui :ocean:

#112 📐 Créditos logos pulidos
  aplicaciones/www/estaticos/imagenes/nacional_2_5.webp
  aplicaciones/www/estaticos/imagenes/nacional_3_4.webp
  aplicaciones/www/src/pages/creditos.astro
Labels: front-end :art:, necesita ayuda :mega:

#116 ✂️ Cueris Descripcion YA
  aplicaciones/www/src/componentes/DescripcionYa.astro
  aplicaciones/www/src/componentes/Menu.astro
  aplicaciones/www/src/scss/_constantes.scss
  aplicaciones/www/src/scss/estilos.scss
Labels: ui :ocean:
