Repository enflujo/imagina-ninezya, pull requests merged in 2023-10, with the labels that each got.

#22 Versión 1 del mapa detalle.
  aplicaciones/www/src/components/Mapa.astro
  aplicaciones/www/src/components/MapaDetalle.astro
  aplicaciones/www/src/pages/index.astro
  aplicaciones/www/src/utilidades/cerebro.ts
Labels: api :evergreen_tree:, front-end :art:

#28 🐛 Arreglar error al quitar deptos
  aplicaciones/www/src/pages/index.astro
Labels: bicho :bug:

#30 🐛 Correción hover y subrayado indicador
  aplicaciones/www/src/componentes/Menu.astro
Labels: ui :ocean:

#29 ✨ Agregar menuú desplegable años
  aplicaciones/www/src/componentes/Mapa.astro
  aplicaciones/www/src/componentes/MapaDetalle.ts
  aplicaciones/www/src/componentes/SelectorNivel.astro
  aplicaciones/www/src/pages/index.astro
Labels: front-end :art:

#34 📝 Actualizar lista de indicadores en menú
  aplicaciones/www/src/datosVisibles/indicadores.ts
Labels: optimización :zap:

#37 🐺 Avances varios
  aplicaciones/www/src/componentes/Mapa.astro
  aplicaciones/www/src/componentes/Menu.astro
  aplicaciones/www/src/componentes/MenuAnios.astro
  aplicaciones/www/src/pages/index.astro
  aplicaciones/www/src/utilidades/cerebro.ts
Labels: front-end :art:

#40 🍎 Eso no es una manzana, es un tomate y rutas del proyecto
  aplicaciones/procesador/fuente/aplicacion.ts
  aplicaciones/procesador/fuente/indicadores/01-01.ts
  aplicaciones/procesador/fuente/indicadores/01-02.ts
  aplicaciones/procesador/fuente/modulos/VariableSingular.ts
  aplicaciones/procesador/fuente/tipos.ts
  aplicaciones/www/src/componentes/Encabezado.astro
  aplicaciones/www/src/componentes/Mapa.astro
  aplicaciones/www/src/componentes/Menu.astro
  aplicaciones/www/src/componentes/SelectorNivel.astro
  aplicaciones/www/src/datosVisibles/indicadores.ts
  aplicaciones/www/src/pages/[ya]/[indicador].astro
  aplicaciones/www/src/pages/[ya]/index.astro
  aplicaciones/www/src/pages/index.astro
  aplicaciones/www/src/plantillas/Principal.astro
  aplicaciones/www/src/scss/_normalizar.scss
  aplicaciones/www/src/scss/estilos.scss
  aplicaciones/www/src/utilidades/cerebro.ts
Labels: front-end :art:

#44 🐛 Definir dirección indicador
  aplicaciones/www/src/componentes/Mapa.astro
  aplicaciones/www/src/utilidades/cerebro.ts
Labels: bicho :bug:
