Repository enflujo/imagina-ninezya, pull requests merged in 2023-12, with the labels that each got.

#121 ✨ Ficha técnica en datos
  aplicaciones/www/src/componentes/FichaTecnica.astro
  aplicaciones/www/src/componentes/Menu.astro
  aplicaciones/www/src/componentes/PropuestaIndicador.astro
  aplicaciones/www/src/pages/[ya]/[indicador].astro
  aplicaciones/www/src/pages/datos.astro
Labels: front-end :art:

#122 ✨ Corrección de márgenes de menú y mapa bienvenida
  aplicaciones/www/src/componentes/Menu.astro
  aplicaciones/www/src/pages/index.astro
Labels: bicho :bug:, front-end :art:, ui :ocean:

#131 🥇 Arreglar umbral al cambiar tamaño de ventana
  aplicaciones/www/src/componentes/FichaTecnica.astro
  aplicaciones/www/src/componentes/LineaTiempo.astro
  aplicaciones/www/src/utilidades/constantes.ts
Labels: bicho :bug:

#135 🐛 Arreglar indicadores suigeridos en pantallas
  aplicaciones/www/src/componentes/LineaTiempo.astro
  aplicaciones/www/src/componentes/PropuestaIndicador.astro
  aplicaciones/www/src/scss/estilos.scss
Labels: bicho :bug:, front-end :art:

#139 ⚡️ Corregir indicadores y agregar umbral
  aplicaciones/www/src/componentes/FichaTecnica.astro
  aplicaciones/www/src/componentes/LineaTiempo.astro
  aplicaciones/www/src/componentes/Mapa.astro
  aplicaciones/www/src/datosVisibles/ya1.ts
  aplicaciones/www/src/datosVisibles/ya10.ts
  aplicaciones/www/src/datosVisibles/ya2.ts
  aplicaciones/www/src/datosVisibles/ya3.ts
  aplicaciones/www/src/datosVisibles/ya4.ts
  aplicaciones/www/src/datosVisibles/ya8.ts
  aplicaciones/www/src/datosVisibles/ya9.ts
  aplicaciones/www/src/pages/[ya]/[indicador].astro
  aplicaciones/www/src/pages/index.astro
  aplicaciones/www/src/tipos.ts
Labels: api :evergreen_tree:, front-end :art:

#156 🧋 Correcciones varias (indicadores y otras)
  aplicaciones/www/src/datosVisibles/ya1.ts
  aplicaciones/www/src/datosVisibles/ya10.ts
  aplicaciones/www/src/datosVisibles/ya2.ts
  aplicaciones/www/src/datosVisibles/ya3.ts
  aplicaciones/www/src/datosVisibles/ya4.ts
  aplicaciones/www/src/datosVisibles/ya5.ts
  aplicaciones/www/src/datosVisibles/ya6.ts
  aplicaciones/www/src/datosVisibles/ya7.ts
  aplicaciones/www/src/datosVisibles/ya8.ts
  aplicaciones/www/src/datosVisibles/ya9.ts
Labels: documentación :book:, front-end :art:

#157 💄 Revisión de textos 1
  aplicaciones/www/src/componentes/FichaTecnica.astro
  aplicaciones/www/src/componentes/PropuestaIndicador.astro
  aplicaciones/www/src/datosVisibles/ya1.ts
  aplicaciones/www/src/datosVisibles/ya10.ts
  aplicaciones/www/src/datosVisibles/ya2.ts
  aplicaciones/www/src/datosVisibles/ya3.ts
  aplicaciones/www/src/datosVisibles/ya4.ts
  aplicaciones/www/src/datosVisibles/ya5.ts
  aplicaciones/www/src/datosVisibles/ya6.ts
  aplicaciones/www/src/datosVisibles/ya7.ts
  aplicaciones/www/src/datosVisibles/ya8.ts
  aplicaciones/www/src/datosVisibles/ya9.ts
  aplicaciones/www/src/pages/creditos.astro
  aplicaciones/www/src/pages/datos.astro
  aplicaciones/www/src/pages/index.astro
  aplicaciones/www/src/scss/estilos.scss
Labels: documentación :book:

#160 👷 Más cambios ya 10
  aplicaciones/www/src/datosVisibles/ya10.ts
Labels: documentación :book:

#161 🍇 Uva color íconos línea de tiempo
  aplicaciones/www/estaticos/iconos/ya1.svg
  aplicaciones/www/estaticos/iconos/ya10.svg
  aplicaciones/www/estaticos/iconos/ya2.svg
  aplicaciones/www/estaticos/iconos/ya3.svg
  aplicaciones/www/estaticos/iconos/ya4.svg
  aplicaciones/www/estaticos/iconos/ya5.svg
  aplicaciones/www/estaticos/iconos/ya6.svg
  aplicaciones/www/estaticos/iconos/ya7.svg
  aplicaciones/www/estaticos/iconos/ya8.svg
  aplicaciones/www/estaticos/iconos/ya9.svg
  aplicaciones/www/estaticos/imagenes/mapa2.svg
  aplicaciones/www/estaticos/imagenes/mapa3.svg
  aplicaciones/www/src/componentes/LineaTiempo.astro
  aplicaciones/www/src/componentes/Menu.astro
Labels: ui :ocean:
